//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ProxyTrabajador {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdentificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Identificacion {
            get {
                return this.IdentificacionField;
            }
            set {
                if ((this.IdentificacionField.Equals(value) != true)) {
                    this.IdentificacionField = value;
                    this.RaisePropertyChanged("Identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyTrabajador.IWSPersona")]
    public interface IWSPersona {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersona/ObtenerPersonas", ReplyAction="http://tempuri.org/IWSPersona/ObtenerPersonasResponse")]
        WebApplication1.ProxyTrabajador.Persona[] ObtenerPersonas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersona/ObtenerPersonas", ReplyAction="http://tempuri.org/IWSPersona/ObtenerPersonasResponse")]
        System.Threading.Tasks.Task<WebApplication1.ProxyTrabajador.Persona[]> ObtenerPersonasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersona/ObtenerPersona", ReplyAction="http://tempuri.org/IWSPersona/ObtenerPersonaResponse")]
        WebApplication1.ProxyTrabajador.Persona ObtenerPersona(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersona/ObtenerPersona", ReplyAction="http://tempuri.org/IWSPersona/ObtenerPersonaResponse")]
        System.Threading.Tasks.Task<WebApplication1.ProxyTrabajador.Persona> ObtenerPersonaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersona/ActualizarPersona", ReplyAction="http://tempuri.org/IWSPersona/ActualizarPersonaResponse")]
        bool ActualizarPersona(WebApplication1.ProxyTrabajador.Persona dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSPersona/ActualizarPersona", ReplyAction="http://tempuri.org/IWSPersona/ActualizarPersonaResponse")]
        System.Threading.Tasks.Task<bool> ActualizarPersonaAsync(WebApplication1.ProxyTrabajador.Persona dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSPersonaChannel : WebApplication1.ProxyTrabajador.IWSPersona, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPersonaClient : System.ServiceModel.ClientBase<WebApplication1.ProxyTrabajador.IWSPersona>, WebApplication1.ProxyTrabajador.IWSPersona {
        
        public WSPersonaClient() {
        }
        
        public WSPersonaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPersonaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPersonaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPersonaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.ProxyTrabajador.Persona[] ObtenerPersonas() {
            return base.Channel.ObtenerPersonas();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ProxyTrabajador.Persona[]> ObtenerPersonasAsync() {
            return base.Channel.ObtenerPersonasAsync();
        }
        
        public WebApplication1.ProxyTrabajador.Persona ObtenerPersona(int id) {
            return base.Channel.ObtenerPersona(id);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.ProxyTrabajador.Persona> ObtenerPersonaAsync(int id) {
            return base.Channel.ObtenerPersonaAsync(id);
        }
        
        public bool ActualizarPersona(WebApplication1.ProxyTrabajador.Persona dto) {
            return base.Channel.ActualizarPersona(dto);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarPersonaAsync(WebApplication1.ProxyTrabajador.Persona dto) {
            return base.Channel.ActualizarPersonaAsync(dto);
        }

        internal dynamic ObtenerPersona()
        {
            throw new NotImplementedException();
        }
    }
}
